service: product-service
frameworkVersion: '2'

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  environment:
    SQS_URL:
      Ref: ExportProductQueue
    SNS_TOPIC:
      Ref: SNSTopic
  iamRoleStatements:
    - Effect: "Allow"
      Action: "sns:*"
      Resource:
        Ref: SNSTopic

resources:
  Resources:
    ExportProductQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: new-products-queue
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: NEW_PRODUCT_NOTIFIER
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: aleksandr.yankovskiy@gmail.com
        Protocol: email
        TopicArn:
          Ref: SNSTopic
        FilterPolicy:
          status:
            - success
  Outputs:
    ExportProductQueueUrl:
      Value:
        Ref: ExportProductQueue
      Export:
        Name: ExportProductQueueUrl
    ExportProductQueueArn:
      Value:
        Fn::GetAtt: [ExportProductQueue, Arn]
      Export:
        Name: ExportProductQueueArn

functions:
  get-products:
    handler: dist/handler.getProducts
    events:
      - http:
          path: products
          method: get
          cors: true
  get-product:
    handler: dist/handler.getProduct
    events:
      - http:
          path: products/{id}
          method: get
          cors: true
  create-product:
    handler: dist/handler.createProduct
    events:
      - http:
          path: products
          method: post
          cors: true
  export-product:
    handler: dist/handler.exportProduct
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - ExportProductQueue
              - Arn
