service: imported-products
frameworkVersion: '2'

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::product-service.imported-products"
    - Effect: "Allow"
      Action: "s3:*"
      Resource:
        - "arn:aws:s3:::product-service.imported-products/*"

functions:
  import-products-file:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  parse-products-file:
    handler: handler.parseProductsFile
    events:
      - s3:
          bucket: product-service.imported-products
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

