service: product-service
frameworkVersion: '2'

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

functions:
  import-producs-file:
    handler: dist/handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true

